name: Build
on:
  workflow_call:
    inputs:
      node:
        required: true
        type: string
        description: Node version
      os:
        required: true
        type: string
        description: OS environment
    secrets: inherit

jobs:
  build:
    name: lint test build on Node ${{ inputs.node }} and ${{ inputs.os }}

    runs-on: ${{ inputs.os }}

    steps:
      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build
