name: Build-Example
on:
  workflow_call:
    inputs:
      node:
        required: true
        type: string
        description: Node version
      os:
        required: true
        type: string
        description: OS environment
      example_directory:
        default: example
        required: false
        type: string
        description: example directory path

jobs:
  build:
    name: build Example  on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ${{ inputs.example_directory }}

    steps:
      - name: Example - Install deps and build
        uses: bahmutov/npm-install@v1

      - name: Example - Build
        run: yarn build
