name: CI
on:
  push:
  pull_request:
    branches:
      - main
      - dev

env:
  GIT_PKG_PUBLISH_TOKEN: ${{ secrets.PKG_PUBLISH_TOKEN }}

jobs:
  prepare:
    name: Setup Node ${{ matrix.node }} on ${{ matrix.os }}

    strategy:
      matrix:
        node: ['12.x', '14.x', '16.x', '18.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn install --frozen-lockfile --ignore-scripts

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build

      - name: Example - Install deps and build
        uses: bahmutov/npm-install@v1
        with:
          working-directory: example

      - name: Example - Build
        run: yarn build
        working-directory: example

      # - name: Build
      #   uses: ./.github/workflows/build.yml
      #   with:
      #     node: ${{ matrix.node }}
      #     os: ${{ matrix.os }}

      # - name: Build-Example
      #   uses: ./.github/workflows/build-example.yml
      #   with:
      #     node: ${{ matrix.node }}
      #     os: ${{ matrix.os }}

  # build:
  #   name: lint test build on Node ${{ matrix.node }} and ${{ matrix.os }}

  #   runs-on: ${{ matrix.os }}
  #   needs: prepare

  #   steps:
  #     - name: Lint
  #       run: yarn lint

  #     - name: Test
  #       run: yarn test --ci --coverage --maxWorkers=2

  #     - name: Build
  #       run: yarn build

  # build-example:
  #   name: build Example  on Node ${{ matrix.node }} and ${{ matrix.os }}

  #   runs-on: ${{ matrix.os }}
  #   needs: prepare

  #   defaults:
  #     run:
  #       working-directory: example

  #   steps:
  #     - name: Example - Install deps and build
  #       uses: bahmutov/npm-install@v1

  #     - name: Example - Build
  #       run: yarn build
