name: CI
on:
  push:
  pull_request:
    branches:
      - main
      - dev

env:
  GIT_PKG_PUBLISH_TOKEN: ${{ secrets.PKG_PUBLISH_TOKEN }}

jobs:
  run-matrix:
    name: Run CI for Node ${{ matrix.node }} on ${{ matrix.os }}

    strategy:
      matrix:
        node: ['12.x', '14.x', '16.x', '18.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Intro
        run: |
          echo 'Event: ${{ toJSON(github.event) }}'
          echo 'EventName: ${{ github.event_name }}'
          echo 'Ref: ${{ github.ref }}'
          echo 'RefName: ${{ github.ref_name }}'
          echo 'RefType: ${{ github.ref_type }}'

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn install --frozen-lockfile --ignore-scripts

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build

      - name: Example - Install deps and build
        uses: bahmutov/npm-install@v1
        with:
          working-directory: example

      - name: Example - Build
        run: yarn build
        working-directory: example

      - name: Publish
        # if: ${{ github.event_name == 'release' && matrix.node == '12.x' && matrix.os == 'ubuntu-latest' }}
        if: ${{ github.event_name == 'pull_request' && matrix.node == '12.x' && matrix.os == 'ubuntu-latest' }}
        run: |
          echo 'Under Publish'
