name: CI
on:
  push:
  pull_request:
    branches:
      - main
      - dev

env:
  GIT_PKG_PUBLISH_TOKEN: ${{ secrets.PKG_PUBLISH_TOKEN }}

jobs:
  prepare:
    name: Run CI for Node ${{ matrix.node }} on ${{ matrix.os }}

    strategy:
      matrix:
        node: ['12.x', '14.x', '16.x', '18.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: ./.github/workflows/build.yml
        with:
          node: ${{ matrix.node }}
          os: ${{ matrix.os }}
